services:
  - type: web
    name: loveconnect-mongo-backend
    runtime: docker
    dockerfilePath: ./mongo-firebase-agora-app/backend/Dockerfile
    dockerContext: ./mongo-firebase-agora-app/backend
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://love-connect-beta.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: ALLOW_DEV_TOKENS
        value: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
